DangerousPrototypes/BusPirate5-firmware

- commands/global/macro.c
Implemented point A) of  https://forum.buspirate.com/t/ideas-for-executing-bus-syntax-macros-from-file/345/13?u=gabri74
> Use string IDs instead of numeric for macro calling

- display/scope.c
- change grid color to pale yellow
- allow to move 0V level up (one division)
> Scope: minor tweaks to improve signal readability

- commands/global/freq.c
Hello, this is a small checking to improve the f and F command. I think it can be seen as a stop gap until the PIO is used instead of a pwm slice. 
Use autoranging for more precise frequency measurement
Use longer time gate to measure duty cycle for more precision
> Use autoranging for more precise frequency measurement

- commands/global/freq.c
- pirate/freq.pio
Hi Ian, 
I now have some new code to get rid of the pwm and only use PIO. Note that I haven't touched the multiple pins frequency measurement.
> Replace all pwm measurements with PIO programs

- CMakeLists.txt
- bytecode.h
- commands/global/cmd_selftest.c
- display/default.c
- mode/logicanalyzer.c
- msc_disk.c
- pirate.c
- pirate/button.c
- pirate/intercore_helpers.c
- pirate/intercore_helpers.h
- pirate/mcu.c
- ui/ui_process.c
Replaces the following PRs:
* #66
* #67
* #68
* #69
> Merged the multiple small PRs so you don't have to merge / rebase

- pirate/storage.c
> RGB: only need six hex digits printed

- src/commands/global/bug.c
> Add summary to `bug e9`

- src/platform/bpi-rev10.h
- src/platform/bpi-rev8.h
- src/platform/bpi-rev9.h
- src/platform/bpi5-rev10.h
- src/platform/bpi5xl-rev0.h
- src/platform/bpi6-rev1.h
Generally speaking, files should include the headers that they need.   Here, `<stdint.h>` was missing.
> Fix build break that's in main branch

- src/boards/memmap_default_rp2040.ld
- src/boards/memmap_default_rp2350.ld
> Linker to show full 16MB flash

- src/boards/memmap_default_rp2040.ld
- src/boards/memmap_default_rp2350.ld
> Integrate RPi SDK fix for RAM usage output

- .github/workflows/build.yaml
- src/binmode/binio.c
- src/binmode/binio_helpers.c
- src/binmode/legacy4third.c
- src/commands/global/cmd_convert.c
- src/commands/global/disk.c
- src/mjson/mjson.c
- src/syntax.c
- src/toolbars/logic_bar.c
- src/ui/ui_display.c
- src/ui/ui_format.c
- src/ui/ui_lcd.c
- src/ui/ui_mode.c
- src/ui/ui_term.c
- src/usb_rx.c
Many, many small fixes that are trivial.
> Fix issues found by CodeQL

- src/commands/global/otpdump.c
Fixes argument parsing.
Improves usage text (shown with `otpdump -h`).
Changes default to dumping only non-blank OTP.
Changes default to dumping entirety of OTP.
> Improve usage text and defaults for otpdump

- src/binmode/legacy4third.c
With this PR, the SPI Flash Planks will work better out of the box, and WP and HOLD will be customizable when entering the mode.
-----
The idea is that a **novice user** buys the **Plank**, activates the **binmode legacy**, **presses Enter for everything (yes)**, and **Flashrom works correctly** for both **reading and writing with all possible chips**.
> Add friendly Plank support for WP HOLD binmodelegacy

- src/commands/infrared/tvbgone.c
- src/lib/picorvd/PicoSWIO.cpp
- src/lib/picorvd/picoswio.c
Hello, 
I think we should remove the explicit references to the CPU clock speed (125MHz at present).
> Remove known dependencies on the exact CPU clock speed (125MHz)

- src/lib/picofreq/picofreq.c
Sorry, didn't commit this file last time.
> One more 125MHz clock speed dependency

- src/commands/global/v_adc.c
- src/pirate/amux.c
- src/pirate/amux.h
- src/platform/bpi5-rev10.c
- src/platform/bpi5-rev10.h
- src/platform/bpi5-rev8.c
- src/platform/bpi5-rev8.h
- src/platform/bpi5-rev9.c
- src/platform/bpi5-rev9.h
- src/platform/bpi5xl-rev0.c
- src/platform/bpi5xl-rev0.h
- src/platform/bpi6-rev2.c
- src/platform/bpi6-rev2.h
- src/platform/bpi7-rev0.c
- src/platform/bpi7-rev0.h
As discussed in https://forum.buspirate.com/t/adc-averaging-code/1118
Please also cherry pick into the bp7r0 branch so that I can easily use the code there without causing conflicts further down the road.
> Add ADC averaging

- src/commands/global/w_psu.c
- the default was unlimited current before
- caused resets for users that weren't careful to explicitly enable the limit -> better set a default that keeps the BP running and probably the DUT safe
- The default is used in the menu and for the commandline arguments to the W command
- Use 0 to explicitly disable current limiting
As discussed in https://forum.buspirate.com/t/flashing-bootloader-on-nrf52840-with-bp6/1103/35?u=electronic_eel
> set a default current limit of 300mA for the PPSU

- src/pirate.c
- src/usb_rx.c
- src/usb_rx.h
- src/usb_tx.c
- src/usb_tx.h
@DangerousPrototypes 
This is a step in the right direction. It should be ok functionally.
> Fix for uart bridge mode causing loss of USB functionality

- src/commands/global/freq.c
> Proposed fix for "F breaks the PSU"

- src/binmode/legacy4third.c
legacy binmode: I've improved the UI and security based on feedback from the users.
> better and safer UI experience for legacy binmode

- src/binmode/legacy4third.c
delete #if 0 and some comments from legacy4third
> delete #if 0 and some comments from legacy4third

- src/queue.h
See [BusPirate forum discussion](https://forum.buspirate.com/t/lockup-in-queue2/1302/2?u=henrygab) for details on bug.
> Fix for random queue lockups.

- .clang-format_files
- src/CMakeLists.txt
- src/display/default.c
- src/display/disabled.c
- src/display/disabled.h
- src/display/scope.c
- src/displays.c
- src/displays.h
Added in the display mode menu.
> Add display mode to turn screen off.
