DangerousPrototypes/BusPirate5-firmware

usb_descriptors.c

Changed default tinyusb strings to Bus Pirate ones, so the enumerated USB functions have fancier names:

USB string descriptors now mention Bus Pirate

---

commands/global/disk.c

(Forum user: Gabri74)
Fix wrong printf format string (%02d instead of %02x) in the storage hex dump command
NOTE: github diff viewer show an added bracket in this commit at line 270, which is not true. That line was not modified and the bracket already exists in the original file ¯_(ツ)_/¯

Fix storage hex command dump format typo

---

commands/global/disk.c
commands/global/macro.c
pirate/storage.c
pirate/storage.h

This PR moves disk_ls fro macro.c to pirate/storage.c and renames it to storage_ls.
It also add a flags field  to show/hide files/dirs/size/summary.
It uses the new implementation for disk_ls_handler (without -hopefully- changing current listing format) and for macro (showing only files, no dirs, no summary)

Add a flags field in disk_ls (now storage_ls) and integare it into existing code

---

usb_descriptors.c

I believe that it will help people distinguish which CDC port to connect to. Windows should show them -though I have seen some instances where Windows does not display them-
I don't believe it can hurt in any case. 
Thanks

Separate the string descriptors of the two CDC interfaces.

---

commands/global/dummy.c
msc_disk.c
pirate.c

Initially the host view is writable, until the host connects to the BP5. After this point the host view is read only and BP5 writes need to call refresh_usbmsdrive() to get the host view in sync When the connection with the BP5 is closed, the host view becomes writable again TODO:
call refresh_usbmsdrive() to get the host view in sync. sync fatfs on connection to get the host changes
Notes:
the dummy command does call refresh_usbmsdrive() to verify the POC

proof of concept to solve sync between the BP5 and the host.

---

ui/ui_help.c

Fix was tested on device. Solves issue #15 https://github.com/DangerousPrototypes/BusPirate5-firmware/issues/15

Fix for proper reading and threshold value of VRef in SPI flash mode

---

hacks/build_server.md

Added multi-line code formatting tags + extra heading for the webhook.
I had just been reading https://forum.buspirate.com/t/build-server-setup-documentation/369 and noticed an extra heading, so added that in also. I also see there is some commented out lines present here not in the forum post, but I left the rest of the file intact. If you want this to be synced with the content of forum post will do that also.

chore(doc): multiline code tags for build server doc

---

.github/workflows/build.yaml

For easy sanity check, that the build works on all platform after any commit or in pull requests.
Also it will make compiling the firmware easier for novice, because they will be able to let GitHub compile the code for them.
Plus the `build.yml` yaml file can further guide users to how to configure their setup.
I know that you have some automation outside of GitHub, but having automation also here would be nice.

Add GitHub Actions build workflow

---

.github/workflows/build.yaml

v3 checkout and upload-artifact actions have been depreciated for several months now, and the upload-artifact will stop working in November. 
Usage of the v3 actions leads to the first three warnings in the action build summary, due to [NodeJS 16 being EoL](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/), with the last one being regarding upload-artifacts <4 will cease functioning in November. 
One gotcha with the v4 upload-artifact is that it is no longer possible to upload to the same named Artifact multiple times... instead it must be a unique name for each upload, and you can merge them in a later step if necessary.
i.e. I use this in with a other project as we have around 20 different firmware targets, with a unique filename for each, …

fix: action depreciation warnings

---

docker-compose.yml
docker/Dockerfile
docker/entrypoint.sh
readme.md

This provides a docker based build environment to just get up and running quickly with the build. Note that the `buspirate/buspirate_v5` isn't a real image, but maybe someday it can be and can be used in github actions.

feat: Docker build environment

---

mode/sump.c

The forums indicated there wasn't the ability to exit sump mode, so I added the pirate button to do that: https://forum.buspirate.com/t/com-port-issues/247/59
There's not really a contribution guide, so here's what I did for testing:
* build from clean source repo
* tested with pulseview 0.4.2
* connect to bp in binary mode `/dev/ttyACM1`
* run a capture
* push button - verified returned to serial prompt
As always, please let me know if I can provide additional details or a better test method.

feat: button exits osl sump

---

ui/ui_term.c

I fixed a bug, where the recognization of delete key press (`[3~`) fails.  
In addition, I change the behavior of the "delete" key (0x7F) to the behavior of backspace, because that is what most terminals do.

delete key bugfix

---

commands/global/cmd_selftest.c
usb_descriptors.c

Encodes the MCU's 64-bit unique ID as a 16 character hex serial number.
Untested at the moment, awaiting hardware.  Creating PR in case others want to try this / comment.

Enable USB serial number

---

CMakeLists.txt
mode/logicanalyzer.c
pirate/memmap_buspirate5.ld
readme.md

Set the custom linker script 'memmap_buspirate5.ld' for buspirate5. There is no need to patch pico SDK for that
`memmap_buspirate5.ld` is already patched copy of `src/rp2_common/pico_standard_link/memmap_default.ld`

Set custom linker script to memmap_buspirate5.ld

---

commands/global/button_scr.c
commands/global/button_scr.h
commands/global/script.c
commands/global/script.h
pirate.c
pirate/button.c
pirate/button.h

Updated button_irq_callback to handle RISE and FALL(press and release). Added button_long_exec() in button_scr.c. . Added logic in pirate.c to run bulong.scr instead of button.scr on long press.

Updated button_irq_callback to discern between long and short button presses

---

mode/logicanalyzer.c
mode/logicanalyzer.h
mode/logicanalyzer.pio
mode/sump.c

Logic analyzer code cleanup, fix potential race condition, edge triggering support
sump support for edge triggering
pio code cleanup (shorter) and edge triggering support
@DangerousPrototypes I found the root cause of the sigrok problem. It is due to the 3rd party library libserialport. It lacks a proper handling of the Windows overlapped IO feature. I partially rewrote the OLS support just because it was quite inefficient but I believe that the original code would work with a fixed libserialport. I also added edge triggering to the OLS support. I do have a fixed Windows pulseview  setup program but I lack a place to upload it. If you could tell me where to upload it, I will do so.

LA and sump improvement / cleanup

---

CMakeLists.txt
nand/attic/shell_cmd.c
nand/nand_ftl_diskio.c
nand/spi_nand.c
nand/spi_nand.h

* Add new target in CMakefiles.txt
* Change NAND terms to use `ERASE_BLOCK` instead of simply `BLOCK`
* Use `#define` to select between two flash chips for firmware
* Pass `row_address_t` to additional nand functions to support multi-plane
* Fix for cross-plane copy (less efficient, but required until command found that copies from one plane's cache register to the other plane's cache register...)
( Replaces PR #65  )

Enable 2Gbit rev10 board firmware

---

CMakeLists.txt
commands/global/cmd_selftest.c
commands/global/freq.c
commands/global/pwm.c
fatfs/diskio.c
pirate.c
pirate.h
pirate/amux.c
pirate/button.c
pirate/lcd.c
pirate/psu.c
pirate/pullup.c
pirate/rgb.c
pirate/storage.c

_Note: It is recommended to review the changes on a per-commit basis._
* Change `BP_VER` --> `BP_VERSION` and `BP_REV` --> `BP_BOARD_REVISION`
* Change `BP_VERSION` to use non-numeric values
`BP_VER` and `BP_REV` are easily confused as they look similar, especially true for those with dyslexia.  Using more descriptive defines improves readability.
`BP_VERSION` is changed to be one of `BP5`, `BP5XL`, `BP6` for consistency.  Use of strings is intentional to clarify that checks that `BP_VERSION < 5` (or similar numeric comparisons) are subtle problems that may be difficult to diagnose/root cause.
`BP_BOARD_REVISION` remains a numeric value, but should only be used in combination with a check of `BP_VERSION`.
I also renamed a few internal aspects of the pixels code.

Various QoL updates

---

fatfs/ff.c
msc_disk.c
msc_disk.h
nand/nand_ftl_diskio.c
pirate.c

Bunch of fixes to fix the hand over of the file system changes between BP and the host (At least Windows). 
Support for Windows device eject command. 
After all file system object writes, the BP mass storage is ejected and re-inserted to force Windows to notice the changed storage. 
By analyzing the USB MSC traffic between a well known Trenscend SD card reader I found out and implemented the correct sequence of SENSE CODEs to emit during ejection and insertion of a changed storage system.

PR to fix some problems with the storage 

---

commands/spi/sniff.c

The following is the compiler warning:
```
./commands/spi/sniff.c: In function 'sniff_handler':
./commands/spi/sniff.c:78:8: warning: 'ui_help_show' reading 4 bytes from a region of size 0 [-Wstringop-overread]
78 |     if(ui_help_show(res->help_flag,usage,count_of(usage), &options[0],count_of(options) )) return;
|        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./commands/spi/sniff.c:78:8: note: referencing argument 2 of type 'const char * const[0]'
In file included from ./commands/spi/sniff.c:17:
./ui/ui_help.h:10:6: note: in a call to function 'ui_help_show'
10 | bool ui_help_show(bool help_flag, const char * const usage[], uint32_t count_of_usage, const struct ui_help_options *options, uint32_t count_of_options);
|      ^~~~~~~~~~~~
```
I've …

quiet a long-standing compiler warning

---

hacks/show_port_info.ps1

1. Open a Windows Powershell command prompt
2. Change to the directory containing the powershell script
3. Review the contents of the script (for malicious content)
4. If necessary, permit the loading of the # execute as follows:
5. If satisfied with content, permit the loading of the script:
`Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process`
6. Load the script into your current Powershell process
`. .\show_port_info.ps1`
7. Run the main function that the script defined
`Get-BusPirateDetails`
The following is an example, with a single BusPirate5 device connected:
```txt
PS C:\Users\ian> Get-BusPirateDetails
InstanceId          : USB\VID_1209&PID_7331\FEDCBA9876543210
Serial              : FEDCBA9876543210
Location            : Port_#0003.Hub_#0007
InstanceID_Terminal : …
```

Powershell script to which serial ports are for which function

---

.gitignore
hacks/build_server.md
hacks/build_server_condensed.md
readme.md

Fix some formatting issues with prior update to `./readme.md`.
Documentation suggests the use of more descriptive build directory names:
* `./build_rp2040`
* `./build_rp2350`
Build server documentation also now uses the more descriptive build directory names.
_Note: Github actions currently continue to simply build in `./build`, as they build only one architecture per task, and thus do not have cross-architecture pollution concerns._

Better build directory naming

---

hacks/show_port_info.ps1

Also added more explicit documentation on how to use
the script, both from a Windows Powershell prompt, as
well as from a  Windows Command Prompt (cmd.exe).

Fix a typo in the diagnostic powershell script

---

src/bytecode.h
src/mode/binloopback.c
src/mode/dummy1.c
src/mode/hw1wire.c
src/mode/hw2wire.c
src/mode/hwhduart.c
src/mode/hwi2c.c
src/mode/hwled.c
src/mode/hwuart.c
src/syntax.c
src/syntax.h
src/ui/ui_mode.c
src/ui/ui_process.c
src/ui/ui_process.h

The switch used to run bus syntax has been turned into an array of functions to reduce overhead and make things more readable.
It does not yet work. I intend to rework how we pass and manage the in and out data packet pointers.

Syntax run rework to reduce overhead

---

hacks/88-buspirate.rules

Users still have to manually install the rules ... this just provides a starting point.
Rules perform THREE key tasks:
1. sets the group owner to `dialout`
2. sets permissions to `0660` so `dialout` group gets read and write access to the `/dev/ttyACM` instance
3. creates symbolic links for the two CDC interfaces:
*  `/dev/buspirate-N` is for the serial console COM port
* `/dev/buspirate-bin-N` is for the binary COM port

Add sample udev rules

---

src/commands/global/bug.c

Minor fix to output of `bug e9 -a` to properly indicate which IO is being tested and/or exhibits the errata.

Fix output to not always say IO0

---

src/debug_rtt.c
src/debug_rtt.h
src/pirate.c

Minor cleanup so default debug options are set in `debug_rtt.c`.
Helper function for debug print macros:
* forced to be always inline for zero perf difference vs. macro
* provides better type safety and error messages if types are mismatched
* also increases clarity of `BP_DEBUG_PRINT` macro

Consolidate default debug settings

---

src/pirate.c
src/pirate.h
src/pirate/storage.c
src/pirate/storage.h
src/system_config.c
src/system_config.h
src/translation/base.c
src/translation/base.h
src/usb_descriptors.c

Fixes #149.
Generally, see `src/pirate.c` around line 76, function `should_disable_unique_usb_serial_number()`.
Five options are listed here, of which four are implemented:
1. Compile-time option ... compatible with existing compile flag (
2. `bpconfig.bp` configuration option ... see `src/pirate/storage.c` for JSON field, and `system_config.disable_unique_usb_serial_number`.
3. Existence of file named `FACTORY.USB` on root of the flash storage.
4. If the file system is not formatted (or DNE for pre-REV10)
Note that factory testing can then use the same firmware as shipped.  When first loading onto the tester, there will be no file system, and thus no unique serial number will be exposed.   The test procedures, when formatting the media, will need to also create the file `FACTORY.USB` to …

Optional usb serial

---

hacks/rtt_debugging.md
src/CMakeLists.txt
src/debug_rtt.c
src/debug_rtt.h
src/nand/spi_nand.c
src/pirate.c
src/pirate.h
src/ui/ui_flags.h
src/usb_rx.c
src/usb_rx.h
src/usb_tx.c

SPI arbitration was broken.  Turns out that releasing a mutex that hasn't been acquired is NOT the right thing to do, and then hiding the problem in a helper function just makes it that much harder to track down the real problem.
This branch also allows the buspirate's terminal to be controlled from RTT.
However, the terminal output is not yet sent over RTT ... so you'll still need to connect a terminal for now.
Related to #110 ... in that it may reduce corruption of the NAND file system by fixing the SPI arbitration.

Technical debt -- and one SPI bus fix

---

readme.md
src/binmode/binio.c
src/binmode/binio_helpers.c
src/binmode/legacy4third.c
src/commands/global/a_auxio.c
src/commands/global/freq.c
src/commands/global/pwm.c
src/commands/global/w_psu.c
src/commands/hdplxuart/bridge.c
src/commands/spi/sniff.c
src/commands/uart/monitor.c
src/debug_uart.c
src/mode/dio.c
src/mode/dummy1.c
src/mode/hiz.c
src/mode/hw1wire.c
src/mode/hw2wire.c
src/mode/hw3wire.c
src/mode/hwhduart.c
src/mode/hwi2c.c
src/mode/hwled.c
src/mode/hwspi.c
src/mode/hwuart.c
src/mode/infrared.c
src/nand/spi.c
src/syntax.c
src/system_config.c
src/system_config.h
src/ui/ui_const.h

* Remove unused return value from three functions
* Rename two functions to reflect their purpose
* Fixed a typo in a comment
* Fixed array of strings to be correctly sized
* Fixed documentation to include parallel builds using `cmake` from command line
All changes are functionally equivalent to prior behavior.
Fixes #177

Payoff some technical debt

---

src/pirate.c
src/pirate/intercore_helpers.h
src/ui/ui_statusbar.c

Prior fix attempt was incompleted, broke in commit c5aba879c18ea838176578a0d9b2fb086ed92f03.
While prior fix worked in that it prevented corruption of the status bar buffer, it failed to set a necessary variable and thus the status bar was **_never_** updated.

fix regression: missing status bar

---

.github/workflows/build.yaml
.github/workflows/codeql.yml

At present this is limited to C/CPP.
Because it is unclear if CodeQL can merge multiple jobs for a single language,
everything is performed within a single job.
Also, enable `--parallel` for all CMake builds.

Enable CodeQL scanning

---

src/translation/editor/translation_editor.html
src/translation/templates/it-it.json

Also used this UI to confirm base EN-US string
was the likely source for many IT-IT string translations.

Enable copy-to-clipboard

---

docker/Dockerfile

Fixes #199 
Before:
```
...
TinyUSB available at /opt/pico-sdk/lib/tinyusb/src/portable/raspberrypi/rp2040; enabling build support for USB.
BTstack available at /opt/pico-sdk/lib/btstack
cyw43-driver available at /opt/pico-sdk/lib/cyw43-driver
lwIP available at /opt/pico-sdk/lib/lwip
mbedtls available at /opt/pico-sdk/lib/mbedtls
CMake Error at /opt/pico-sdk/tools/CMakeLists.txt:125 (message):
Incompatible picotool installation found: Requires version 2.1.0, you have
version 2.0.0
Update your installation, or set PICOTOOL_FORCE_FETCH_FROM_GIT to download
and build the correct version
Call Stack (most recent call first):
/opt/pico-sdk/tools/CMakeLists.txt:485 (pico_init_picotool)
/opt/pico-sdk/src/cmake/on_device.cmake:57 (picotool_postprocess_binary)
src/CMakeLists.txt:547 …
```

upgrade picotool to 2.1.0 to enable build

---

src/binmode/falaio.c
src/binmode/sump.c
src/commands/global/cmd_mcu.c
src/commands/global/cmd_selftest.c
src/lib/picorvd/picoswio.c
src/otp/bp_otp.h
src/otp/bp_otp_rw.c
src/otp/bp_whitelabel.c
src/pirate.c
src/pirate/button.c
src/pirate/hw2wire.pio
src/pirate/hwi2c.pio
src/pirate/hwuart.pio
src/pirate/rgb.c
src/usb_descriptors.c

NOTE: This PR is to a branch ... not to main.
This was manually verified by stepping through the whitelabel code using RTT on a fresh (unused) PICO board.
Other changes include:
* Add TODO to document why rp2040 pio programs differ from rp2350 (GPIO pulldown)
* Defined `STRDEF` structure for USB Whitelabel
* Defined helper function to verify the range of OTP rows used by the USB Whitelabel data
* OTP is no longer soft-locked after boot (!!!)
* Whitelabel now refers to INFO_UF2.TXT BoardID field as ... board id (not "manufacturing data")
* BoardID is now the serial number, per Ian's code fragment
* Updated other serial number displays to match the format from Ian's code fragment
* Update USB serial number ... align with other uses (transform to hex a byte at a time, not nybble).

1-step automated USB whitelabel

---

src/binmode/fala.c
src/binmode/falaio.c
src/binmode/logicanalyzer.c
src/binmode/logicanalyzer.h
src/toolbars/logic_bar.c

Replaced the 4 dma data channels with 1 dma data channel and 1 control channel. This allows to free 2 dma channels and lift any alignment restriction on the la_buff buffer. Now there is only one buffer segment, so the code is simplified. 
Also replaced some hard coded values (0x1ffff) that represented the la_buffer size -1

simplify the logic analyzer DMA structure.

---

src/commands/global/freq.c

@DangerousPrototypes 
This is the 2 fixes I talked about: 
sync  freq_timer_callback and freq_measure_period_irq
remove the code that goes through the pwm output and add them to the mask.

Another fix for frequency measurement
